# Generated by Django 4.1.5 on 2023-02-13 06:15

import blog.custom_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', blog.custom_field.UnsignedAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='태그명')),
                ('page_title', models.CharField(default='', max_length=255, verbose_name='태그페이지 제목')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='태그에 대한 요약 설명')),
                ('count', models.IntegerField(default=0, editable=False, verbose_name='게시글 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TagArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_manager.tag')),
            ],
            options={
                'db_table': 'tag_article_rel',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='tag_manager.TagArticle', to='blog.article'),
        ),
    ]
